### ISSUE TITLE
tag a stable version

### ISSUE THREAD

**Issue by metalmumu** [TheBigBrainsCompany/TbbcRestUtilBundle#7]
There has been a fix in the Configuration class to fix a fatal error with Symfony 5, but this fix is not in a tag

**Comment by armetiz** [comment]
Hey @metalmumu . Tag v1.0.3 has been pushed.

Thanks

**Comment by metalmumu** [comment]
The package has to be updated manually on packagist, otherwise the new tag is not accessible
https://packagist.org/packages/tbbc/rest-util-bundle
